# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-ast
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: check-illegal-windows-names
    -   id: detect-private-key
    -   id: fix-byte-order-marker

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.5
    hooks:
    # Run the linter.
    -   id: ruff
        name: Lint with Ruff
        args: [ --fix ]
        exclude: .*/migrations/
    # Run the import sorter
    # -   id: ruff
    #     name: sort imports with ruff
    #     args: [--select, I, --fix]
    #     exclude: .*/migrations/
    # Run the formatter.
    -   id: ruff-format
        name: Format with Ruff
        exclude: .*/migrations/

-   repo: https://github.com/pycqa/bandit
    rev: 1.8.6
    hooks:
      - id: bandit
        args: ["-ii", "-ll"]

-   repo: local
    hooks:
    -   id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        # entry: bash -c 'trufflehog git file://. --since-commit HEAD --results=verified,unknown --fail'
        # For running trufflehog in docker, use the following entry instead:
        entry: bash -c 'docker run --rm -v "$(pwd):/workdir" -i --rm trufflesecurity/trufflehog:latest git file:///workdir --since-commit HEAD --results=verified,unknown --fail'
        language: system
        stages: ["pre-commit", "pre-push"]
