# Generated by Django 5.2.7 on 2025-10-27 20:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the activity", max_length=100),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the activity"
                    ),
                ),
                (
                    "durationMinutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimated duration of the activity in minutes",
                        null=True,
                    ),
                ),
                (
                    "difficultyLevel",
                    models.IntegerField(
                        blank=True,
                        default=1,
                        help_text="1 (easy) to 5 (hard)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "coachingPoints",
                    models.TextField(
                        blank=True, help_text="Key coaching points for the activity"
                    ),
                ),
                (
                    "safetyConsiderations",
                    models.TextField(
                        blank=True, help_text="Safety considerations for the activity"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the location within the venue",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the location"
                    ),
                ),
                (
                    "coordinates",
                    models.CharField(
                        blank=True,
                        help_text="GPS coordinates of the location",
                        max_length=50,
                    ),
                ),
                (
                    "terrainType",
                    models.CharField(
                        blank=True,
                        help_text="Type of terrain (e.g., paved, gravel, grass)",
                        max_length=50,
                    ),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True, help_text="Notable features of the location"
                    ),
                ),
                (
                    "terrainDifficulty",
                    models.IntegerField(
                        blank=True,
                        default=1,
                        help_text="1 (easy) to 5 (hard)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the venue", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the venue"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        help_text="Physical address of the venue", max_length=255
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=15
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Contact email address", max_length=254
                    ),
                ),
                (
                    "riskAssessmentUrl",
                    models.URLField(
                        blank=True,
                        help_text="URL to the venue's risk assessment document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="activityEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_needed",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Quantity of this equipment needed for the activity",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.activity"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="activityImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imageUrl",
                    models.ImageField(
                        help_text="Image of the activity", upload_to="activity_images/"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description of the image"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.activity"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the equipment", max_length=100),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the equipment"
                    ),
                ),
                (
                    "quantityAvailable",
                    models.IntegerField(
                        blank=True,
                        help_text="Quantity of this equipment available",
                        null=True,
                    ),
                ),
                (
                    "safetyInstructions",
                    models.TextField(
                        blank=True,
                        help_text="Safety instructions for using the equipment",
                    ),
                ),
                (
                    "activities",
                    models.ManyToManyField(
                        related_name="equipment_items",
                        through="core.activityEquipment",
                        to="core.activity",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activityequipment",
            name="equipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.equipment"
            ),
        ),
        migrations.CreateModel(
            name="locationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imageUrl",
                    models.ImageField(
                        help_text="Image of the location", upload_to="location_images/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.location"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="location",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.venue"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activityequipment",
            unique_together={("activity", "equipment")},
        ),
    ]
