# Generated by Django 5.2.7 on 2025-10-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipment",
            name="activities",
            field=models.ManyToManyField(
                related_name="equipment_items",
                through="core.ActivityEquipment",
                to="core.activity",
            ),
        ),
    ]
