# Generated by Django 5.2.7 on 2025-10-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_equipment_activities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venue",
            name="name",
            field=models.CharField(
                help_text="Name of the venue",
                max_length=100,
                unique=True,
                verbose_name="Venue Name",
            ),
        ),
    ]
