# Generated by Django 5.2.7 on 2025-10-28 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_team_alter_activity_coachingpoints_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_date",
                    models.DateField(
                        help_text="Date of the planned session",
                        verbose_name="Session Date",
                    ),
                ),
                (
                    "session_time",
                    models.TimeField(
                        help_text="Start time of the session",
                        verbose_name="Session Time",
                    ),
                ),
                (
                    "session_length_minutes",
                    models.PositiveIntegerField(
                        help_text="Duration of the session in minutes",
                        verbose_name="Session Length",
                    ),
                ),
                (
                    "group_size",
                    models.PositiveIntegerField(
                        help_text="Expected number of participants",
                        verbose_name="Group Size",
                    ),
                ),
                (
                    "age_range",
                    models.CharField(
                        help_text="Age range of participants (e.g., '8-10', '14+', 'Adult')",
                        max_length=50,
                        verbose_name="Age Range",
                    ),
                ),
                (
                    "ability_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("mixed", "Mixed Abilities"),
                        ],
                        default="mixed",
                        help_text="Overall ability level of the group",
                        max_length=20,
                        verbose_name="Ability Level",
                    ),
                ),
                (
                    "coaches_required",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of coaches needed for this session",
                        verbose_name="Coaches Required",
                    ),
                ),
                (
                    "plan_goal",
                    models.TextField(
                        help_text="Main objective or goal for this session",
                        verbose_name="Session Goal",
                    ),
                ),
                (
                    "owner_team",
                    models.ForeignKey(
                        blank=True,
                        help_text="Team that owns this object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_owned_objects",
                        to="core.team",
                        verbose_name="Owner Team",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        help_text="Where the session will take place",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.venue",
                        verbose_name="Venue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PlanSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of this section (e.g., 'Warm-up', 'Main Activity', 'Cool Down')",
                        max_length=100,
                        verbose_name="Section Name",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which this section appears in the plan",
                        verbose_name="Order",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="core.plan",
                        verbose_name="Plan",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("plan", "order")},
            },
        ),
        migrations.CreateModel(
            name="PlanSectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which this item appears in the section",
                        verbose_name="Order",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("location", "Location"),
                            ("activity", "Activity"),
                            ("note", "Note"),
                        ],
                        max_length=20,
                        verbose_name="Item Type",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or free-form content for this item",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional duration for this item in minutes",
                        null=True,
                        verbose_name="Duration",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.activity",
                        verbose_name="Activity",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.location",
                        verbose_name="Location",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.plansection",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("section", "order")},
            },
        ),
    ]
