# Generated by Django 5.2.7 on 2025-10-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_plan_plansection_plansectionitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="coach_qualification_required",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I2C BMX Freestyle", "I2C BMX Freestyle"),
                    ("I2C BMX Race", "I2C BMX Race"),
                    ("I2C Cycle Speedway", "I2C Cycle Speedway"),
                    ("I2C Cycling", "I2C Cycling"),
                    ("I2C Off-Road", "I2C Off-Road"),
                    ("I2C Road", "I2C Road"),
                    ("I2C Track", "I2C Track"),
                    ("CIC BMX Freestyle", "CIC BMX Freestyle"),
                    ("CIC BMX Race", "CIC BMX Race"),
                    ("CIC CX", "CIC CX"),
                    ("CIC MTB XC", "CIC MTB XC"),
                    ("CIC MTB Gravity", "CIC MTB Gravity"),
                    ("CIC Road", "CIC Road"),
                    ("CIC Track", "CIC Track"),
                ],
                help_text="Required coach qualification for this session (optional)",
                max_length=50,
                null=True,
                verbose_name="Coach Qualification Level Required",
            ),
        ),
    ]
